In [4]:
import html
import re
from collections import Counter

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from matplotlib import style
from wordcloud import WordCloud, STOPWORDS
from sklearn.model_selection import train_test_split

style.use('ggplot')

SEED = 42

# Chỉ dùng khi vẽ WordCloud/thống kê từ,
# không xóa khỏi dữ liệu đưa vào model.
eda_stop_words = set(STOPWORDS) - {
    'not', 'no', 'nor', 'never'
}

In [5]:

#Xử lý các review
def data_processing(text):
    text = html.unescape(str(text))
    text = text.lower()

    # Xóa các biến thể của <br>
    text = re.sub(r'<br\s*/?>', '', text)

    # Xóa HTML tag còn lại
    text = re.sub(r'<[^>]+>', '', text)

    # Xóa URL
    text = re.sub(
        r'https?://\S+|www\.\S+',
        ' ', text
    )

    # Giữ chữ, số, khoảng trắng và dấu nháy đơn
    text = re.sub( r"[^a-z0-9\s']",' ',text)

    # Chuẩn hóa khoảng trắng
    text = re.sub(r'\s+', ' ', text).strip()

    return text

```
"This movie is really good"
        ↓
Tokenizer của DistilBERT
        ↓
input_ids + attention_mask
        ↓
DistilBERT
        ↓
Classification Head
        ↓
0 hoặc 1
        ↓
Negative / Positive
```

## 1. Import thư viện

In [6]:
import numpy as np
import torch

from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer)

from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support)

## 2. Check data

In [7]:
import pandas as pd

train_df = pd.read_csv("train.csv")
validation_df = pd.read_csv("validation.csv")
test_df = pd.read_csv("test.csv")

train_df["clean_review"] = (
    train_df["clean_review"].astype(str)
)
validation_df["clean_review"] = (
    validation_df["clean_review"].astype(str)
)
test_df["clean_review"] = (
    test_df["clean_review"].astype(str)
)

train_df["label"] = train_df["label"].astype("int64")
validation_df["label"] = (
    validation_df["label"].astype("int64")
)
test_df["label"] = test_df["label"].astype("int64")

print("Train:", train_df.shape)
print("Validation:", validation_df.shape)
print("Test:", test_df.shape)

Train: (34703, 2)
Validation: (7437, 2)
Test: (7437, 2)

In [8]:
print("Train shape:", train_df.shape)
print("Validation shape:", validation_df.shape)
print("Test shape:", test_df.shape)

print("\nTrain:")
display(train_df.head())

print("\nLabel distribution:")
print(train_df['label'].value_counts())

Train shape: (34703, 2)
Validation shape: (7437, 2)
Test shape: (7437, 2)

Train:

                                        clean_review  label
0  due to the invention of a the domestication co...      1
1  wow so much fun probably a bit much for normal...      1
2  the abc gears up it's repertory company for an...      0
3  being in the suburbs of new york when the z bo...      1
4  this was soul provoking i am an iranian and li...      1

Label distribution:
label
1    17416
0    17287
Name: count, dtype: int64

## 3. Convert từ pandas sang huggingface

### Lý do chuyển đổi
- Tối ưu bộ nhớ
- Tương thích với PyTorch / TensorFlow
<small>_Cấu trúc Dataset của Hugging Face được thiết kế riêng để tự động chuyển đổi dữ liệu thành các Tensor (torch.Tensor hoặc tf.Tensor)_</small>

In [9]:
train_dataset = Dataset.from_pandas(train_df, preserve_index=False)

validation_dataset = Dataset.from_pandas(validation_df, preserve_index=False)

test_dataset = Dataset.from_pandas(test_df, preserve_index=False)

print(train_dataset)
print(validation_dataset)
print(test_dataset)

Dataset({
    features: ['clean_review', 'label'],
    num_rows: 34703
})
Dataset({
    features: ['clean_review', 'label'],
    num_rows: 7437
})
Dataset({
    features: ['clean_review', 'label'],
    num_rows: 7437
})

## 4. Chọn model

In [10]:
MODEL_NAME = "distilbert-base-uncased"

# 5. Tạo tokenizer

In [11]:
tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

# 6. Test tokenizer

In [12]:
example = train_df['clean_review'].iloc[0]

print("Original:")
print(example)

print("\nTokens:")
print(tokenizer.tokenize(example)[:50])

print("\nEncoded:")
print(tokenizer(example))

Original:
due to the invention of a the domestication collar flesh eating zombies are brought under control and become productive members of society however they perform menial tasks the servile dead attend to those living in fenced us 1950s styled small towns while untamed zombies roam around in the wild zone in the town of willard pre teen k'sun ray as timmy robinson lives with parents carrie anne moss and dylan baker as helen and bill robinson alas the robinsons are the only family on their street who do not own a zombie their new neighbors the bottoms have six so to keep up the robinsons obtain zombie billy connolly as fido unfortunately mr connolly's domestication collar is damaged by an old lady's walker and he eats her then new and hungry zombies infest the town meanwhile young ray has grown attached to connolly the boy and his zombie are like tv's timmy and lassie and the robinson family find it difficult to cooperate with the controlling zomcom authorities fido doesn't go far enough into its own intriguing wild zone but it is a colorful stylish and amusingly satirical addition to zombie film lore ray and the cast perform well individually with nubile zombie sonja bennett as tammy and owner tim blake nelson as theopolis the most memorable pair director andrew currie and crew including rob gray design jan kiesser photography don macdonald music and james willcock design deservedly won awards fido 2006 andrew currie k'sun ray carrie anne moss billy connolly dylan baker

Tokens:
['due', 'to', 'the', 'invention', 'of', 'a', 'the', 'domestic', '##ation', 'collar', 'flesh', 'eating', 'zombies', 'are', 'brought', 'under', 'control', 'and', 'become', 'productive', 'members', 'of', 'society', 'however', 'they', 'perform', 'men', '##ial', 'tasks', 'the', 'ser', '##vil', '##e', 'dead', 'attend', 'to', 'those', 'living', 'in', 'fence', '##d', 'us', '1950s', 'styled', 'small', 'towns', 'while', 'un', '##tam', '##ed']

Encoded:
{'input_ids': [101, 2349, 2000, 1996, 11028, 1997, 1037, 1996, 4968, 3370, 9127, 5771, 5983, 14106, 2024, 2716, 2104, 2491, 1998, 2468, 13318, 2372, 1997, 2554, 2174, 2027, 4685, 2273, 4818, 8518, 1996, 14262, 14762, 2063, 2757, 5463, 2000, 2216, 2542, 1999, 8638, 2094, 2149, 4856, 13650, 2235, 4865, 2096, 4895, 15464, 2098, 14106, 25728, 2105, 1999, 1996, 3748, 4224, 1999, 1996, 2237, 1997, 19138, 3653, 9458, 1047, 1005, 3103, 4097, 2004, 27217, 6157, 3268, 2007, 3008, 13223, 4776, 10636, 1998, 7758, 6243, 2004, 6330, 1998, 3021, 6157, 21862, 2015, 1996, 6157, 2015, 2024, 1996, 2069, 2155, 2006, 2037, 2395, 2040, 2079, 2025, 2219, 1037, 11798, 2037, 2047, 10638, 1996, 24196, 2031, 2416, 2061, 2000, 2562, 2039, 1996, 6157, 2015, 6855, 11798, 5006, 21018, 2004, 10882, 3527, 6854, 2720, 21018, 1005, 1055, 4968, 3370, 9127, 2003, 5591, 2011, 2019, 2214, 3203, 1005, 1055, 5232, 1998, 2002, 20323, 2014, 2059, 2047, 1998, 7501, 14106, 1999, 14081, 1996, 2237, 5564, 2402, 4097, 2038, 4961, 4987, 2000, 21018, 1996, 2879, 1998, 2010, 11798, 2024, 2066, 2694, 1005, 1055, 27217, 1998, 27333, 2666, 1998, 1996, 6157, 2155, 2424, 2009, 3697, 2000, 17654, 2007, 1996, 9756, 1062, 5358, 9006, 4614, 10882, 3527, 2987, 1005, 1056, 2175, 2521, 2438, 2046, 2049, 2219, 23824, 3748, 4224, 2021, 2009, 2003, 1037, 14231, 2358, 8516, 4509, 1998, 19142, 2135, 17251, 2804, 2000, 11798, 2143, 19544, 4097, 1998, 1996, 3459, 4685, 2092, 14258, 2007, 16371, 14454, 2063, 11798, 2365, 3900, 8076, 2004, 19971, 1998, 3954, 5199, 6511, 5912, 2004, 14833, 17699, 1996, 2087, 13432, 3940, 2472, 4080, 20667, 1998, 3626, 2164, 6487, 3897, 2640, 5553, 11382, 7971, 2121, 5855, 2123, 10406, 2189, 1998, 2508, 2097, 13959, 2640, 10849, 2135, 2180, 2982, 10882, 3527, 2294, 4080, 20667, 1047, 1005, 3103, 4097, 13223, 4776, 10636, 5006, 21018, 7758, 6243, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

## 7. Tokenizer cho dataset

In [13]:
MAX_LENGTH = 128

def tokenize_function(batch):
    return tokenizer(
        batch['clean_review'],
        truncation=True, # Cắt câu dài hơn MAX_LENGTH
        max_length=MAX_LENGTH)

# Gắn số (tra dictionary) cho dataset
tokenized_train = train_dataset.map(tokenize_function, batched=True)

tokenized_validation = validation_dataset.map(tokenize_function, batched=True)

tokenized_test = test_dataset.map(tokenize_function, batched=True)


print(tokenized_train[0])

Map:   0%|          | 0/34703 [00:00<?, ? examples/s]

Map:   0%|          | 0/7437 [00:00<?, ? examples/s]

Map:   0%|          | 0/7437 [00:00<?, ? examples/s]

{'clean_review': "due to the invention of a the domestication collar flesh eating zombies are brought under control and become productive members of society however they perform menial tasks the servile dead attend to those living in fenced us 1950s styled small towns while untamed zombies roam around in the wild zone in the town of willard pre teen k'sun ray as timmy robinson lives with parents carrie anne moss and dylan baker as helen and bill robinson alas the robinsons are the only family on their street who do not own a zombie their new neighbors the bottoms have six so to keep up the robinsons obtain zombie billy connolly as fido unfortunately mr connolly's domestication collar is damaged by an old lady's walker and he eats her then new and hungry zombies infest the town meanwhile young ray has grown attached to connolly the boy and his zombie are like tv's timmy and lassie and the robinson family find it difficult to cooperate with the controlling zomcom authorities fido doesn't go far enough into its own intriguing wild zone but it is a colorful stylish and amusingly satirical addition to zombie film lore ray and the cast perform well individually with nubile zombie sonja bennett as tammy and owner tim blake nelson as theopolis the most memorable pair director andrew currie and crew including rob gray design jan kiesser photography don macdonald music and james willcock design deservedly won awards fido 2006 andrew currie k'sun ray carrie anne moss billy connolly dylan baker", 'label': 1, 'input_ids': [101, 2349, 2000, 1996, 11028, 1997, 1037, 1996, 4968, 3370, 9127, 5771, 5983, 14106, 2024, 2716, 2104, 2491, 1998, 2468, 13318, 2372, 1997, 2554, 2174, 2027, 4685, 2273, 4818, 8518, 1996, 14262, 14762, 2063, 2757, 5463, 2000, 2216, 2542, 1999, 8638, 2094, 2149, 4856, 13650, 2235, 4865, 2096, 4895, 15464, 2098, 14106, 25728, 2105, 1999, 1996, 3748, 4224, 1999, 1996, 2237, 1997, 19138, 3653, 9458, 1047, 1005, 3103, 4097, 2004, 27217, 6157, 3268, 2007, 3008, 13223, 4776, 10636, 1998, 7758, 6243, 2004, 6330, 1998, 3021, 6157, 21862, 2015, 1996, 6157, 2015, 2024, 1996, 2069, 2155, 2006, 2037, 2395, 2040, 2079, 2025, 2219, 1037, 11798, 2037, 2047, 10638, 1996, 24196, 2031, 2416, 2061, 2000, 2562, 2039, 1996, 6157, 2015, 6855, 11798, 5006, 21018, 2004, 10882, 3527, 6854, 2720, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

## 8. Padding trong cùng batch

In [14]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [15]:
import random
import numpy as np
import torch

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

## 9. Load DistilBERT

In [16]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME,num_labels=2,
    id2label={ # Số sang chữ
        0: "NEGATIVE",
        1: "POSITIVE"
    },
    label2id={ # Chữ sang số
        "NEGATIVE": 0,
        "POSITIVE": 1
    }
)

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## 10. Metric

In [22]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred

    predictions = np.argmax(
        predictions, # Số bên nào lớn hơn thì mô hình nghiêng về nhãn đó
        axis=1 # Tìm vị trí của số lớn nhất trong cặp số đó để chốt câu trả lời cuối cùng của mô hình là 0 hay 1
    )

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average='binary', # Phân loại nhị phân
        zero_division=0 # Ép chia cho 0 tránh crash
    )

    accuracy = accuracy_score(
        labels,
        predictions
    )



    return {
        'accuracy': accuracy, # Độ chính xác tổng thể
        'precision': precision, # Độ chính xác khi đoán nhãn POSITIVE (Thư viện mặc định coi nhãn 1 POSITIVE - mục tiêu (Positive Class), còn nhãn 0 là nhãn phụ)
        'recall': recall, # Nhận diện sót
        'f1': f1, # Điểm số cân bằng giữa precision và recall

    }

## 11. Cấu hình Fine-tuning

In [19]:
training_args = TrainingArguments(
    output_dir="./distilbert_imdb",

    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,

    num_train_epochs=2,
    weight_decay=0.01,

    fp16=torch.cuda.is_available(),

    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,

    logging_steps=100,
    seed=SEED,
    report_to="none")

## 12. Train

In [23]:
trainer = Trainer(
    model=model,
    args=training_args,

    train_dataset=tokenized_train,
    eval_dataset=tokenized_validation,

    processing_class=tokenizer,
    data_collator=data_collator,

    compute_metrics=compute_metrics)

train_result = trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

## 13. Validation

In [24]:
validation_results = trainer.evaluate(tokenized_validation)

print(validation_results)

{'eval_loss': 0.5519840121269226, 'eval_accuracy': 0.8879924700820223, 'eval_precision': 0.8819810326659642, 'eval_recall': 0.8968657915885347, 'eval_f1': 0.8893611369371762}

## 14. Test

In [25]:
test_results = trainer.evaluate(tokenized_test)

print(test_results)

{'eval_loss': 0.5198456048965454, 'eval_accuracy': 0.8925642059970418, 'eval_precision': 0.8913797704830531, 'eval_recall': 0.894962486602358, 'eval_f1': 0.8931675357668137}

## 15. Bonus: Xử lý kết quả dự đoán

```python
probabilities = torch.softmax(outputs.logits, dim=1)
predicted_label = probabilities.argmax(dim=1).item()
confidence = probabilities.max().item()
```

### `probabilities`

Chuyển điểm thô `logits` của model thành xác suất bằng hàm `softmax`.

```text
Logits:       [-1.2, 2.8]
                  ↓ softmax
Probabilities: [0.018, 0.982]
```

Kết quả:

```text
NEGATIVE: 1.8%
POSITIVE: 98.2%
```

### `predicted_label`

Lấy vị trí của xác suất lớn nhất để xác định nhãn dự đoán.

```text
Probabilities: [0.018, 0.982]
                         ↑ lớn nhất

predicted_label = 1
```

Quy ước:

```text
0 = NEGATIVE
1 = POSITIVE
```

=> `POSITIVE`.

### `confidence`

Lấy xác suất lớn nhất để biểu thị độ tin cậy của model.

```text
max(0.018, 0.982) = 0.982
```

Khi đổi sang phần trăm:

```text
Confidence = 98.2%
```

Tóm tắt:

```text
softmax → chuyển logits thành xác suất
argmax  → chọn nhãn dự đoán
max     → lấy độ tin cậy
```

In [26]:
test_reviews = [
    "This movie was amazing and I really enjoyed it.",
    "This movie was boring and completely terrible."
]

# train() huấn luyện
model.eval() # Chế độ dự đoán

for review in test_reviews:
    cleaned_review = data_processing(review)

    inputs = tokenizer( # Tokenize văn bản
        cleaned_review,
        return_tensors="pt",
        truncation=True,
        max_length=MAX_LENGTH,
        padding=True
    ).to(model.device)

    with torch.no_grad():
        outputs = model(**inputs)

    probabilities = torch.softmax(outputs.logits, dim=1)
    predicted_label = probabilities.argmax(dim=1).item()
    confidence = probabilities.max().item()

    sentiment = "POSITIVE" if predicted_label == 1 else "NEGATIVE"

    print(f"Review: {review}")
    print(f"Prediction: {sentiment} ({confidence:.2%})")
    print()

Review: This movie was amazing and I really enjoyed it.
Prediction: POSITIVE (99.95%)

Review: This movie was boring and completely terrible.
Prediction: NEGATIVE (99.96%)